repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
    args: ["--allow-multiple-documents"]
  - id: debug-statements
  - id: trailing-whitespace
    exclude: >-
      ^.*.md$

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.2
  hooks:
  - id: ruff-format
  - id: ruff
    args: [ --fix, --exit-non-zero-on-fix ]

- repo: local
  hooks:
  - id: typecheck
    name: typecheck
    entry: mypy .
    types: [python]
    language: system
    pass_filenames: false
