[tool.black]
target-version = ['py38']
force-exclude = '''
'''

[tool.isort]
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
force_grid_wrap = 0
line_length = 88
length_sort = true
lines_between_types = 1

[tool.pytest.ini_options]
addopts = "-vv --cov pink_accents"
testpaths = ["tests"]
