name: CI
on:
  pull_request:
    branches:
    - "*"
  push:
    branches:
    - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    # because pre-commit uses external mypy
    - name: install mypy
      run: |
        pip install -U pip
        pip install mypy .
    - uses: pre-commit/action@v3.0.0

  test:
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: install pytest
      run: |
        pip install -U pip
        pip install .
        pip install pytest
    - run: pytest
